blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView
)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('', include('blog.urls')),
    path('topics/', include('topics.urls')),
    path('research/', include('research.urls')),
    path('report/', include('report.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

topics/urls.py
from django.urls import path
from . import views


from .views import (
    KeywordListView,
    KeywordDetailView,
    KeywordCreateView,
    KeywordUpdateView,
    KeywordDeleteView,
    UserKeywordListView
)

urlpatterns = [
    path('', KeywordListView.as_view(), name='keyword-home'),
    path('user/<str:username>', UserKeywordListView.as_view(), name='user-keywords'),
    path('keyword/<int:pk>/', KeywordDetailView.as_view(), name='keyword-detail'),
    path('keyword/new/', KeywordCreateView.as_view(), name='keyword-create'),
    path('keyword/<int:pk>/update/', KeywordUpdateView.as_view(), name='keyword-update'),
    path('keyword/<int:pk>/delete/', KeywordDeleteView.as_view(), name='keyword-delete'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from topics.models import Keyword
from ckeditor_uploader.fields import RichTextUploadingField


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = RichTextUploadingField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    keywords = models.ManyToManyField(Keyword,max_length=255)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

report/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from topics.models import Keyword
from ckeditor_uploader.fields import RichTextUploadingField


class Record(models.Model):
    class Rate(models.TextChoices):
        Potential = 1, 'potential'
        Evaluating = 2, 'evaluating'
        NoPotential = 3, 'nopotential'
    niches = models.CharField(max_length=255)
    project = models.CharField(max_length=255)
    token = models.CharField(max_length=255)
    ecosystem = models.CharField(max_length=255)
    launch = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    website = models.URLField(max_length=255)
    twitter = models.CharField(max_length=255)
    overview = models.TextField(max_length=255)
    comment = models.TextField(max_length=255)
    rate = models.CharField(
        max_length = 2,
        choices=Rate.choices,
        default=Rate.Evaluating
    )
    content = RichTextUploadingField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    keywords = models.ManyToManyField(Keyword,max_length=255)


    def __str__(self):
        return self.project
        
    def get_absolute_url(self):
        return reverse('record-detail', kwargs={'pk': self.pk})

research/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from topics.models import Keyword
from ckeditor_uploader.fields import RichTextUploadingField


class Proposal(models.Model):
    title = models.CharField(max_length=100)
    business_model = models.TextField()
    hr_partner = models.TextField()
    finance = models.TextField()
    technology = models.TextField()
    partner_user_ecosystem = models.TextField()
    community = models.TextField()
    roadmap = models.TextField()
    competitor = models.TextField()
    marketcap = models.TextField()
    tokenomics = models.TextField()
    fomo = models.TextField() 
    content = RichTextUploadingField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    keywords = models.ManyToManyField(Keyword,max_length=255)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('proposal-detail', kwargs={'pk': self.pk})

topics/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Keyword(models.Model):
  name = models.CharField(max_length=100, unique=True)
  description = models.TextField(max_length=255)
  followedbys = models.ManyToManyField(User)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('keyword-detail', kwargs={'pk': self.pk})

topics/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Keyword


def home(request):
    context = {
        'keywords': Keyword.objects.all()
    }
    return render(request, 'topics/home.html', context)



class KeywordListView(ListView):
    model = Keyword
    template_name = 'topics/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'keywords'
    # ordering = ['-date_posted']
    paginate_by = 5


class UserKeywordListView(ListView):
    model = Keyword
    template_name = 'topics/user_keywords.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'keywords'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
 
        return Keyword.objects.filter(author=user)


class KeywordDetailView(DetailView):
    model = Keyword


class KeywordCreateView(LoginRequiredMixin, CreateView):
    model = Keyword
    fields = ['name', 'description', 'followedbys']

    def form_valid(self, form):
        # form.instance.author = self.request.user
        return super().form_valid(form)

class KeywordUpdateView(LoginRequiredMixin, UpdateView):
    model = Keyword
    fields = ['name', 'description', 'followedbys']

    def form_valid(self, form):
        return super().form_valid(form)



class KeywordDeleteView(LoginRequiredMixin, DeleteView):
    model = Keyword
    success_url = '/'

topics/templates/topics/home.html
{% extends "blog/base.html" %}
{% block content %}
    {% for keyword in keywords %}
        <article class="media content-section">
          
          <div class="media-body">
            
            <h2><a class="article-title" href="{% url 'keyword-detail' keyword.id %}">{{ keyword.name }}</a></h2>
            <p class="article-content">{{ keyword.description }}</p>
            <p class="article-content">followed by {% for author in keyword.followedbys.all %}</p>
            <a href="{% url 'profile' %}">{{ author.username }}</a>
            {% endfor %}

            <p class="article-content">all posts: {% for post in keyword.post_set.all %}
            
            <a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a>

            {% endfor %}</p>

            <p class="article-content">all proposals: {% for proposal in keyword.proposal_set.all %}
            
              <a class="article-title" href="{% url 'proposal-detail' proposal.id %}">{{ proposal.title }}</a>
  
              {% endfor %}</p>

              <p class="article-content">all records: {% for record in keyword.record_set.all %}
            
                <a class="article-title" href="{% url 'record-detail' record.id %}">{{ record.project }}</a>
    
                {% endfor %}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}

topics/templates/topics/keyword_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Topic</legend>
                <h2>Are you sure you want to delete the post "{{ object.name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

topics/templates/topics/keyword_detail.html
{% extends "blog/base.html" %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
      
        
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'keyword-update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'keyword-delete' object.id %}">Delete</a>
          </div>
        
      </div>
      <h2 class="article-title">{{ object.name }}</h2>
      <p class="article-content">{{ object.description }}</p>
      <p class="article-content"> followed by: {% for a in object.followedbys.all %}
      {{ a }}
      {% endfor %}</p>
      <p class="article-content">all posts: {% for post in object.post_set.all %}
      <a href="{% url 'post-detail' post.id %}">  {{ post.title }}</a>
      {% endfor %}</p>

      <p class="article-content">all proposals: {% for proposal in object.proposal_set.all %}
        <a href="{% url 'proposal-detail' proposal.id %}">  {{ proposal.title }}</a>
        {% endfor %}</p>
        <p class="article-content">all records: {% for record in object.record_set.all %}
          <a href="{% url 'record-detail' record.id %}">  {{ record.project }}</a>
          {% endfor %}</p>
          
    </div>
  </article>
{% endblock content %}

topics/templates/topics/keyword_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Topics</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Create</button>
            </div>
        </form>
    </div>
{% endblock content %}

topics/templates/topics/users_keyword.html
{% extends "blog/base.html" %}
{% block content %}
    <h1 class="mb-3">Topics followed by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for keyword in keywords %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
            <h2>{{ keyword.name }}</h2>
            <p class="article-content">{{ keyword.description }}</p>
            <p class="article-content">followed by: {% for author in keyword.followedbys.all %}</p>
            <a href="{% url 'keyword-detail' .id %}">{{ author }}</a>
            {% endfor %}
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}